// NOTE: This file is generated by uniwind and it should not be edited manually.
/// <reference types="uniwind/types" />

declare module 'uniwind' {
    export interface UniwindConfig {
        themes: readonly ['light', 'dark', 'opencode-light', 'opencode-dark', 'dracula-light', 'dracula-dark', 'nord-light', 'nord-dark', 'ayu-light', 'ayu-dark', 'cursor-light', 'cursor-dark', 'palenight-light', 'palenight-dark', 'rosepine-light', 'rosepine-dark', 'vercel-light', 'vercel-dark', 'kanagawa-light', 'kanagawa-dark', 'orng-light', 'orng-dark', 'catppuccin-macchiato-light', 'catppuccin-macchiato-dark', 'catppuccin-light', 'catppuccin-dark', 'mercury-light', 'mercury-dark', 'cobalt2-light', 'cobalt2-dark', 'aura-light', 'aura-dark', 'gruvbox-light', 'gruvbox-dark', 'lucent-orng-light', 'lucent-orng-dark', 'monokai-light', 'monokai-dark', 'catppuccin-frappe-light', 'catppuccin-frappe-dark', 'nightowl-light', 'nightowl-dark', 'zenburn-light', 'zenburn-dark', 'matrix-light', 'matrix-dark', 'tokyonight-light', 'tokyonight-dark', 'flexoki-light', 'flexoki-dark', 'everforest-light', 'everforest-dark', 'vesper-light', 'vesper-dark', 'github-light', 'github-dark', 'material-light', 'material-dark', 'solarized-light', 'solarized-dark', 'one-dark-light', 'one-dark-dark', 'synthwave84-light', 'synthwave84-dark']
    }
}

export {}
